spring:
  application:
    name: client1

server:
  port: 7002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
        # 是否要将自身的实例信息注册到 Eureka 服务端
        #register-with-eureka: false
      # 是否从 Eureka 服务端获取注册信息
    #fetch-registry: false

